# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{flattr_rest}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Hansson"]
  s.date = %q{2010-10-18}
  s.description = %q{An OAuth wrapper to make it easier to consume the flattr rest api}
  s.email = %q{joel.hansson@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "lib/flattr_rest.rb",
     "lib/flattr_rest/category.rb",
     "lib/flattr_rest/exception.rb",
     "lib/flattr_rest/flattr_rest.rb",
     "lib/flattr_rest/language.rb",
     "lib/flattr_rest/model.rb",
     "lib/flattr_rest/thing.rb",
     "lib/flattr_rest/user.rb",
     "spec/flattr_rest_spec.rb",
     "spec/sample_data/categories.xml",
     "spec/sample_data/languages.xml",
     "spec/sample_data/one_thing.xml",
     "spec/sample_data/things.xml",
     "spec/sample_data/user_info.xml",
     "spec/sample_data/user_things.xml",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flattr/ruby-flattr-rest}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Flattr.com rest api client}
  s.test_files = [
    "spec/flattr_rest_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<oauth>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<oauth>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

